###
POST http://localhost:8080/users/?id=22332&name=aaaaa&aget=33
Content-Type: application/json

{
"id":"22",
"name":"zd",
"age":23
}

###
GET http://localhost:8080/users/

###
PUT  http://localhost:8080/users/22/?id=22332&name=AAAA&aget=33

###
DELETE http://localhost:8080/users/22332

###
